/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package com.zqy.wherevalidate;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int EQUAL = 3;
  /** RegularExpression Id. */
  int LESS_EQUAL = 4;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 5;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 6;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 7;
  /** RegularExpression Id. */
  int NO_EQUAL = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int TIMES = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int OPEN_PAR = 13;
  /** RegularExpression Id. */
  int CLOSE_PAR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int DIGITS = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int LIKE = 23;
  /** RegularExpression Id. */
  int NOT_LIKE = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<NUMBER>",
    "<DIGITS>",
    "<STRING>",
    "<LETTER>",
    "<IN>",
    "<LIKE>",
    "<NOT_LIKE>",
  };

}
